<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{a869b3f0-a614-425f-b084-f76c1c447cf6}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	//alias
    _FLOAT_TestSuite : _FLOAT_TestSuite;
	_HRESULT_TestSuite : _HRESULT_TestSuite;
    
	// struct
	_TIMESTRUCT_TestSuite : _TIMESTRUCT_TestSuite;
	
	// enums
	_E_TcEventClass_TestSuite : _E_TcEventClass_TestSuite;
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[TcUnit.RUN();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>